### ISSUE TITLE
More explanatory text w/ the logo 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BNHM/berkeleymapper#49] opened 2015-03-25 17:41 UTC
```
 From Joyce Gross: "In BM1, there was an option to display a little bit of text above the map, along with logos. In BM2 we can now display logos with links to other sites. But as far as I know we can't include any text to the left of the map, where the logos are. Is it possible for you to add this? As part of the BM2 xml configuration, similar to the way we configure logos to appear?"
```

Original issue reported on code.google.com by `jdec...@gmail.com` on 22 Dec 2012 at 1:31

**Comment by jdeck88** [comment] 2016-06-01 13:46
This has been fixed-- a duplicate of #61

**Closed by jdeck88** 2016-06-01 13:46 UTC
Labels: auto-migrated, bug, Priority-Medium
